project:
  type: website
  resources:
    - googlec936a5cde75aef0b.html

website:
  title: "Charlotte Kuberka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: CV.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
